import {
    UPDATE_CURRENT_RATIO,
    UPDATE_ASSETS_AND_LIABILITIES,
    UPDATE_INVENTORY_CYCLE_RATE,
    UPDATE_ACCOUNT_RECEIVABLE_CYCLE_RATE,
    UPDATE_TOTAL_ASSETS_TURNOVER,
    UPDATE_GROSS_PROFIT_RATE,
    UPDATE_ROE,
    UPDATE_OPERATION_INCOME_GROWTH_RATE,
    UPDATE_NET_PROFIT_GROWTH_RATE,
    UPDATE_NET_PROFIT_CASH_RATIO
 } from '../actions/firmDataAction';

 